### PR TITLE
Support mongoose single nested schemas (as of 4.3.2)

### PR DESCRIPTION
**Pull request by aliatsis**

### CODE REVIEW

**Comment by joegoldbeck** [comment]
Thanks for the pull request @aliatsis! Can you give me some context as to the purpose of these changes? In particular, a test that fails before these changes and passes after them would be awesome

**Comment by joegoldbeck** [comment]
@aliatsis?

**Comment by aliatsis** [comment]
Sorry for the delay @joegoldbeck. Mongoose recently began supporting Single Nested Schema (as of 4.2.x I think).

var SingleNestedSchema = new Schema({
  hello: String
});

var ParentSchema = new Schema({
  singleNested: SingleNestedSchema
});

These are different than EmbeddedDocuments and don't have a modelName directly associated (other than through the parent schema).

Just added a couple quick tests. There are probably some other test cases that could be valuable to add as well.

Let me know your thoughts. When I originally made this PR there were some bugs in mongoose with single nested schemas. I contributed a PR for one (https://github.com/Automattic/mongoose/pull/3687).
I've been using the newest mongoose versions alongside my fork with this PR and it's been working as expected.

**Comment by joegoldbeck** [comment]
Thanks for the quick response (2 months ago...)! Haven't had a chance to look quite yet, but wanted to let you know it's still on my radar.

**Comment by joegoldbeck** [comment]
I suspect https://github.com/joegoldbeck/mongoose-encryption/pull/51 covers this case as well. Sorry for the delay in merging this :/

**Pull request closed without merging**
