### PR TITLE
Update for compatibility with Uint8Array buffers

### LINKED ISSUE #28: Failing Test on Node v4.1.0
Am getting the following
```
document.save() "before each" hook:
     Uncaught TypeError: Not a buffer
    at TypeError (native)
    at new Decipheriv (crypto.js:235:16)
    at Object.Decipheriv (crypto.js:232:12)
    at model.schema.methods.decryptSync (/Users/Downloads/mongoose-encryption-master/index.js:379:27)
    at Function.invoke (/Users/Downloads/mongoose-encryption-master/node_modules/sinon/lib/sinon/spy.js:156:55)
    at model.proxy [as decryptSync] (/Users/Downloads/mongoose-encryption-master/node_modules/sinon/lib/sinon/spy.js:82:26)
    at model.<anonymous> (/Users/Downloads/mongoose-encryption-master/index.js:312:17)
    at EventEmitter.<anonymous> (/Users/Downloads/mongoose-encryption-master/node_modules/mongoose/lib/schema.js:781:17)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
    at model.Document.(anonymous function) [as emit] (/Users/Downloads/mongoose-encryption-master/node_modules/mongoose/lib/document.js:88:42)
    at /Users/Downloads/mongoose-encryption-master/node_modules/mongoose/lib/model.js:268:13
    at /Users/Downloads/mongoose-encryption-master/node_modules/mongoose/lib/model.js:127:7
    at /Users/Downloads/mongoose-encryption-master/node_modules/mongodb/lib/collection.js:449:5
    at /Users/Downloads/mongoose-encryption-master/node_modules/mongodb/lib/collection.js:593:5
    at /Users/Downloads/mongoose-encryption-master/node_modules/mongodb/lib/bulk/unordered.js:457:9
    at resultHandler (/Users/Downloads/mongoose-encryption-master/node_modules/mongodb/lib/bulk/unordered.js:409:5)
    at /Users/Downloads/mongoose-encryption-master/node_modules/mongodb-core/lib/topologies/server.js:756:13
    at [object Object].Callbacks.emit (/Users/Downloads/mongoose-encryption-master/node_modules/mongodb-core/lib/topologies/server.js:95:3)
    at [object Object].messageHandler (/Users/Downloads/mongoose-encryption-master/node_modules/mongodb-core/lib/topologies/server.js:243:23)
    at Socket.<anonymous> (/Users/Downloads/mongoose-encryption-master/node_modules/mongodb-core/lib/connection/connection.js:262:22)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)
``

### PR DESCRIPTION
**Pull request by foster**
Not safe for merge, since this depends on an unreleased version of mongoose.

### CODE REVIEW

**Comment by foster** [comment]
:+1: External dependency resolved. Ready to merge. Fixes #28

**Comment by joegoldbeck** [comment]
Hi @foster and thanks for looking into this! That's awesome that it resolves with almost no work on our end. One issue with the PR - the Mongoose version in the package.json doesn't actually affect the version used by the consumer of this plugin - they specify that themselves in the package.json in their end. Somehow we need to check the version they are using and throw an error if it's earlier than 4.2.4 and they are using >= Node 4.0. Hopefully, that gets passed in with the schema here https://github.com/foster/mongoose-encryption/blob/master/index.js#L74 . I should have time to look into it at the end of this week if you don't before then!

Thanks again for tracking down the primary issues!

**Comment by joegoldbeck** [comment]
Actually, that said, the PR as it stands is already an improvement. Merging.

**Comment by joegoldbeck** [comment]
Published as 1.2.2

**Comment by foster** [comment]
True, the version of `mongoose` should be left to the user of this package, not this package itself. In fact, it may make sense to treat `mongoose` as a `peerDependency` rather than as a `dependency`.

As for how to express "Works with `mongoose 4.1.x` on Node 0.12 but `mongoose >=4.2.4` on Node 4/5"... I don't know. You could do a runtime check and die/warn at initialization, but then you'd also get in the business of comparing semver numbers. Seemed easier to just bump the dependency :smiley:

**Pull request merged**
