### PR TITLE
Fix: decryption when fields change

### LINKED ISSUE #48: How to decrypt an encrypted field
Is there a possible way to decrypt a field that I encrypted earlier ?

### LINKED ISSUE #83: Issue decrypting a field
Hi,
I'd like to decrypt the field "content" of my "MessageSchema" so I changed my option from `encryptedFields: ['content']` to `encryptedFields: ['']` but when I do that and I try to do a Find() on a message it's returning me undefined for the "content" field.

Any clue of what might happen ?

PS: If I try to change `encryptedFields: ['']` to `encryptedFields: ['anotherField']` it's giving me the same result

Thanks,
Pierre

### PR DESCRIPTION
**Pull request by joegoldbeck**
Closes #83 
Closes #48

### CODE REVIEW

**Comment by jenyatra** [comment]
I love convenience of this solution for users with existing data (#109 requires complicated migration procedure).

Found a problem with this, still drops the data. A change in test that makes it fail: jenyatra/mongoose-encryption@b5ffa48

When document is decrypted, extra data from _ct not marked modified. Because of that, consequent save won't set it to cleartext.

Possible fix I see is to detect extracted fields list and mark it modified. In #109 it's [done here](https://github.com/jenyatra/mongoose-encryption/blob/92164ac38bbdec156b2cbe214b39b2e28bf21146/lib/plugins/mongoose-encryption.js#L395), but we have access to actual encrypted fields list of a doc there. One unwanted side effect for end users is that a document could appear modified right from beginning.

**Comment by jenyatra** [comment]
Another way is to keep actual decrypted fields for each `Document` instance, and use it to mark extracted fields as modified.

```
schema.methods.decryptSync = function(doc) { 
    ...
    var fieldsToDecrypt = objectUtil.getPaths(decryptedObject);
    ...
    // CHANGE 1: assigning actual decrypted fields to Document instance for late use
    (doc || that).decryptedFields = fieldsToDecrypt
```

Then:
```
schema.methods.encrypt = function(cb) {
    
    
    
```

**Comment by Ryce** [comment]
I just tried merging this commit in a fork I created. It still does not seem to work though, our encrypted data still does not come through. Any idea what the status is with this? Has not been updated for quite a long time

**Comment by joegoldbeck** [comment]
Yeah I think this does not fix it :(. Not sure when I'll have a chance to tackle, but open to other PRs

Closing to avoid misleading folks

**Pull request closed without merging**
