### PR TITLE
marks all authenticated fields as modified when saving

### PR DESCRIPTION
**Pull request by wlingke**

### CODE REVIEW

**Comment by joegoldbeck** [comment]
Hmmm, I'm getting a test failure:

```
document.save() when only certain fields are encrypted should not overwrite _ct or _ac when saved after a find that didnt retrieve _ct or _ac:
     Uncaught AssertionError: expected [Error: Authentication failed] to equal null
    at Promise.<anonymous> (/Users/joe/Source/mongoose-encryption/test/encrypt.coffee:263:18)
```

Also, since you basically have a test case all worked out, do you think you could include a non-promisified version to confirm it solves the issue?

**Comment by joegoldbeck** [comment]
Which makes sense, since it's marking fields as modified which may not have been selected in the query. As signing effectively solidifies the state of all the signed fields, maybe this should take place as part of the `sign` instance method?

**Comment by wlingke** [comment]
Ah yea - we'll probably need to filter the authenticationFields based on if
they are selected. It's not immediately clear to me how to do that at the
moment. I'll try and find some time next week to look.

Regarding the tests, I don't know any coffeescript but happy to write in JS
if you are okay with that.

Finally, I'm not sure if sign method is the right place. This bug is only
applicable in the save method whereas `sign` is used in other places (like
migrate). Also semantically, I feel that sign should be reserved to
creating the buffer and this isn't really related to that. That said - it's
just my opinion - arguments can be made for both view points :).
ᐧ

Best,
Lingke

--
Lingke Wang
Stanford GSB '16

**Comment by joegoldbeck** [comment]
Re: the right place. Your argument seems quite reasonable, I'm happy for it do be as part of the `save`. We actually only sign the document when all authenticated fields have been selected, so no filtering is required. If `markModified` is in the callback for `.sign` within the pre-save hook (it only happens in two places, a couple lines a part, and you'll see they are both behind `allAuthenticationFieldsSelected(...)`), that should work fine.

Re: test, if you write it in js, and put it through [js2coffee](http://js2.coffee/) you should get some passable coffeescript, so that would be awesome! If it needs a bit of cleaning to be more coffeescript-semantic I can do that afterwards

**Comment by wlingke** [comment]
I posted fix, however could not get the full test up. I didn't have time to look through your testing code and properly put my test into it.

I tried to clean up my test code but you will probably need to insert it.. By the way, I remembered that mongoose supports its own promises by default so I used those.

**Pull request merged**
